"use client"
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/shared/Header'
import { ThemeContext } from '@/context'
import Signature from '@/components/shared/Signature'
import { useState } from 'react'
import { AnimatePresence, motion } from "framer-motion";
import { Toaster } from 'react-hot-toast'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [isLoading, setIsLoading] = useState(false)

  setTimeout(() => {
    setIsLoading(true)
  }, 5000)

  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <AnimatePresence>
          {!isLoading ? < Signature /> :
            <ThemeContext>
              <div className='lg:flex lg:flex-row-reverse flex h-screen justify-between w-full  transition-opacity duration-1000'>
                <Header />
                <main className="w-full">
                  <Toaster position='top-center' />
                  {children}
                </main>
              </div>
            </ThemeContext>
          }
        </AnimatePresence>
      </body>
    </html >
  )
}
